-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
	common = {
		style = {
			caret = {
				back = "#1d1d1d",
				fore = "#cb107d"
			},
			comment = {
				fore = "#76bf0e",
				italic = true
			},
			docComment = {
				fore = "#993300",
				italic = true
			},
			docKeyword = {
				bold = true,
				fore = "#663300",
				italic = true
			},
			doubleQuotedString = {
				fore = "#dbc900"
			},
			error = {
				back = "#ff0000",
				eolfilled = true,
				fore = "#ffff00"
			},
			find = {
				back = "#ffff7f"
			},
			foldMargin = {
				back = "#262626",
				fore = "#ffc15f"
			},
			identifier = {
				fore = "#07a1fb"
			},
			inactive = {
				back = "#1f0000",
				eolfilled = true,
				fore = "#fb44ff"
			},
			keyword = {
				bold = true,
				fore = "#e97914"
			},
			label = {
				fore = "#800000"
			},
			number = {
				fore = "#00d0d0"
			},
			operator = {
				bold = true,
				fore = "#d962ff"
			},
			preprocessor = {
				bold = true,
				fore = "#ff961b"
			},
			ref = {
				back = "#55ffff"
			},
			selection = {
				back = "#532622",
				eolfilled = true,
				fore = "#736eff"
			},
			singleQuotedString = {
				fore = "#dbc900"
			},
			unclosedDoubleQuotedString = {
				back = "#1f0000",
				eolfilled = true,
				fore = "#f2fff1"
			},
			unclosedSingleQuotedString = {
				back = "#1f0000",
				eolfilled = true,
				fore = "#fffdea"
			},
			whitespace = {
				fore = "#808080"
			}
		}
	},
	style = {
		[32] = {
			back = "#000000",
			fore = "#f9fdff"
		},
		[33] = {
			back = "#a0a0a0",
			fore = "#ffffff"
		},
		[34] = {
			back = "#009000",
			bold = true,
			fore = "#ffffff"
		},
		[35] = {
			back = "#7861bc",
			bold = true,
			fore = "#ffffff"
		}
	}
}